### PR TITLE
added rpc call getrawmempool

### PR DESCRIPTION
**Pull request by emeth-**
Based off
https://github.com/Peerunity/Peerunity/commit/e72e61508ad87898b0ee929c6b
0f069c53a829c9

### CODE REVIEW

**Comment by Thireus** [comment]
This command is already available in ppcoin:develop branch:

https://github.com/ppcoin/ppcoin/blob/develop/src/rpcblockchain.cpp#L134-L149

Please merge from our develop branch instead.

**Comment by emeth-** [comment]
Thanks for the heads Thireus, I totally missed that!

A bit confused about branching structure. Is develop intended for v0.5 or v0.4.1?

**Comment by Thireus** [comment]
That's a good question, we should ask @sunnyking or @sigmike about it. I'm using the develop branch for various projects as it contains additional useful RPC calls: http://www.peercointalk.org/index.php?topic=3789.0

**Comment by sigmike** [comment]
Develop is currently intended for 0.5. It doesn't include any protocol change yet but there are important changes from Bitcoin 0.8 merge that Sunny would rather make effective during a mandatory upgrade. This branch will probably include cold minting and op_return with 0 amount when they are ready.

So it makes sense to add this RPC to master if it's intended for 0.4.1.

**Comment by emeth-** [comment]
It is indeed intended for 0.4.1 - thanks for the clarification @sigmike

**Comment by sunnyking** [comment]
I will first backport OP_RETURN related commits from bitcoin to both branches and then the needed API's from peerunity into peercoin 0.4.1 (master). Stay tuned.

**Pull request closed without merging**
